module.exports = {
  AUDIO_URL_RECEIVED: "AUDIO_URL_RECEIVED",
  QUEUED_SONG_RECEIVED: "QUEUED_SONG_RECEIVED",
  DEQUEUED_SONG_RECEIVED: "DEQUEUED_SONG_RECEIVED",
  PLAY_NEXT_SONG: "PLAY_NEXT_SONG",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  TOGGLE_FULLSCREEN: "TOGGLE_FULLSCREEN"
};
